### PR TITLE
Port to ESM for 45

### LINKED ISSUE #17: Gnome 45 support
Looks like this extension is not compatible with Gnome 45

```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  @file:///usr/share/gnome-shell/extensions/pip-on-top@rafostar.github.com/prefs.js:2:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  ```
  
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

### PR DESCRIPTION
**Pull request by oscfdezdz**
Fix #17

### CODE REVIEW

**Comment by skgsergio** [comment]
Tested this for some days now and works like a charm. Any chance of updating the extension in the store @Rafostar?

**Comment by sidevesh** [comment]
works for me too, @Rafostar can we get this merged in ?

**Comment by Rafostar** [comment]
Looks good to me, thanks!

**Comment by Scotty-Trees** [comment]
Just upgraded to Fedora 39 from 38 today. Any idea when this awesome extension update will hit the Gnome Extension website so we can get this? Thank you!

**Pull request merged**
